---
title: "data-day1"
author: "Econ Research Group"
date: "February 20, 2020"
output: html_document
---

```{r setup, include=FALSE}
library(reticulate)
library(gitignore)
use_python("C:\\Python27\\python.exe")
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
#git setup

gi_fetch_templates("R")
```


```{r}
multi_family_data <-  read.csv("multi-family-housing.csv")
View(multi_family_data)

multi_change <- 1184 - 732
multi_change

all_homes_data <- read.csv("all-homes-data.csv")
View(all_homes_data)

all_homes_change <- 1435 - 1112
all_homes_change
```

## Difference between multi-family homes and All homes
Multi-Family Difference: `r multi_change` <br/>
All Homes Difference: `r all_homes_change`

```{r}
#data combined with Jan's Data
homeless_data <- read.csv("final_data.csv")
View(homeless_data)

```

## Equation Ideas
$$ \widehat{hpop} = \hat{b}U6 + \hat{b}AvgRent + \hat{b}PCTdisc + \hat{b}pctinv + \hat{b}TotPop $$
$$ \widehat{PCThmlsofciv} = \hat{b}U6 + \hat{b}AvgRent + \hat{b}PCTdisc + \hat{b}pctinv + \hat{b}TotPop $$

//Todo: California, New York, and Utah on their Own

## Equation from Jan:
$$ \widehat{PCThmlsofciv} = \hat{b}u3 + \hat{b}pctdisc + \hat{b}pctinv $$
```{r}
housing_supply <- read.csv("Annual_housing_supply_by_state.csv")
View(housing_supply)
housing_supply_t <- t(housing_supply)
View(housing_supply_t)

```

```{python}


```
